---
title: "Monocle 3"
author: "Kennedi Todd"
date: "9/7/2022"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---

## Working directory
```{r working_directory}
knitr::opts_knit$set(
  root.dir = "/research/labs/neurology/fryer/m214960/Da_Mesquita/scripts/R")
```

## Libraries
```{r}
library(Seurat)
```

## Read data
- Make sure the data is preprocessed, the dimensionality is reduced (UMAP), and the cells clustered before you learn the trajectory graph with Monocle 3 \
```{r}
# read object
endothelial.annotated <- readRDS("../../rObjects/mouse_endothelial_annotated.rds")
DefaultAssay(endothelial.annotated) <- "RNA"
Idents(endothelial.annotated) <- "individual_clusters"

# plot
# plot current UMAP
DimPlot(endothelial.annotated,
        cols = c("firebrick1","gold","green","cyan","blue","darkorchid1", "lightgray"))
```

# Trajectory
- Convert SeuratObject to cell_data_set object \
- Run
```{r}
# start singularity container in linux shell
# singularity exec --nv /research/bsi/tools/biotools/monocle3-R/monocle3-leafcutter.img R

# convert SeuratObject to cell_data_set object
# this is done in the convert_object.R script
```



