---
title: "Gene Enrichment Analysis Heatmap"
author: "Kennedi Todd & Kimberly Olney"
date: "07/12/2022"
output: html_document
---

# Setup
Set working directory for all chunks.
```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/research/labs/neurology/fryer/m214960/Da_Mesquita/scripts/R")
```

Load packages.
```{r packages}

```

Set variables
```{r set_variables}
# variables
sample_order <- c("E3.2M.M","E3.2M.F","E4.2M.M","E4.2M.F",
                  "E3.14M.M","E3.14M.F","E4.14M.M","E4.14M.F")
age_order <- c("2 months","14 months")
sex_order <- c("Male","Female")
isoform_order <- c("E3","E4")
sample_colors <- c("gray","red","orange","yellow","green","blue","purple","pink")
age_colors <- c("darkgray","chartreuse3")
sex_colors <- c("darkgray","purple")
isoform_colors <- c("darkgray","cornflowerblue")

# work in parallel
options(mc.cores = detectCores() - 1)
```

These functions with help simultaneously save plots as a png and pdf.
```{r}
saveToPDF <- function(...) {
    d = dev.copy(pdf,...)
    dev.off(d)
}

saveToPNG <- function(...) {
    d = dev.copy(png,...)
    dev.off(d)
}
```

# Subset data 
We are going to use the up-regulated DEGs for isoform in the Mrc1-high H2-Eb1-low macrophages cluster.
```{r}
data <- read.delim("../../results/DEGs/")
```

