---
title: 'Comparison: 20% vs 50% Ribosomal Cutoff'
author: "Kennedi Todd"
date: "12/6/2022"
output: html_document
---

# 20% Cutoff
## DEG comparison
```{r ribo50_deg_comparison}
# read tables
isoform.df <- read.table(
  "../../../results/ribo_20/allClusters/DEGs/E4_vs_E3_DEGs.tsv",
  sep = "\t", header = TRUE)
age.df <- read.table(
  "../../../results/ribo_20/allClusters/DEGs/14_vs_2_months_DEGs.tsv",
  sep = "\t", header = TRUE)
sex.df <- read.table(
  "../../../results/ribo_20/allClusters/DEGs/female_vs_male_DEGs.tsv",
  sep = "\t", header = TRUE)

# filter
isoform.df <- isoform.df[isoform.df$p_val_adj < 0.05,]
age.df <- age.df[age.df$p_val_adj < 0.05,]
sex.df <- sex.df[sex.df$p_val_adj < 0.05,]

# add columns
direction <- isoform.df$avg_log2FC > 0
direction <- gsub(TRUE, "isoform_up", direction)
direction <- gsub(FALSE, "isoform_down", direction)
isoform.df$direction <- direction
direction <- age.df$avg_log2FC > 0
direction <- gsub(TRUE, "age_up", direction)
direction <- gsub(FALSE, "age_down", direction)
age.df$direction <- direction
direction <- sex.df$avg_log2FC > 0
direction <- gsub(TRUE, "sex_up", direction)
direction <- gsub(FALSE, "sex_down", direction)
sex.df$direction <- direction

# reformat tables
isoform.df2 <- isoform.df %>%
  dplyr::count(cluster,direction) %>%
  tidyr::spread(cluster, n)
age.df2 <- age.df %>%
  dplyr::count(cluster,direction) %>%
  tidyr::spread(cluster, n)
sex.df2 <- sex.df %>%
  dplyr::count(cluster,direction) %>%
  tidyr::spread(cluster, n)

# master table
df <- smartbind(isoform.df2, sex.df2, age.df2)
df
```

## Cells per cluster
```{r}
table(mouse.annotated)
```


# 50% Cutoff
## DEG comparison
```{r ribo50_deg_comparison}
# read tables
isoform.df <- read.table(
  "../../../results/ribo_20/allClusters/DEGs/E4_vs_E3_DEGs.tsv",
  sep = "\t", header = TRUE)
age.df <- read.table(
  "../../../results/ribo_20/allClusters/DEGs/14_vs_2_months_DEGs.tsv",
  sep = "\t", header = TRUE)
sex.df <- read.table(
  "../../../results/ribo_20/allClusters/DEGs/female_vs_male_DEGs.tsv",
  sep = "\t", header = TRUE)

# filter
isoform.df <- isoform.df[isoform.df$p_val_adj < 0.05,]
age.df <- age.df[age.df$p_val_adj < 0.05,]
sex.df <- sex.df[sex.df$p_val_adj < 0.05,]

# add columns
direction <- isoform.df$avg_log2FC > 0
direction <- gsub(TRUE, "isoform_up", direction)
direction <- gsub(FALSE, "isoform_down", direction)
isoform.df$direction <- direction
direction <- age.df$avg_log2FC > 0
direction <- gsub(TRUE, "age_up", direction)
direction <- gsub(FALSE, "age_down", direction)
age.df$direction <- direction
direction <- sex.df$avg_log2FC > 0
direction <- gsub(TRUE, "sex_up", direction)
direction <- gsub(FALSE, "sex_down", direction)
sex.df$direction <- direction

# reformat tables
isoform.df2 <- isoform.df %>%
  dplyr::count(cluster,direction) %>%
  tidyr::spread(cluster, n)
age.df2 <- age.df %>%
  dplyr::count(cluster,direction) %>%
  tidyr::spread(cluster, n)
sex.df2 <- sex.df %>%
  dplyr::count(cluster,direction) %>%
  tidyr::spread(cluster, n)

# master table
df <- smartbind(isoform.df2, sex.df2, age.df2)
df
```